    name: Terraform Destroy

on:
  workflow_dispatch: # Allows manual triggering of this workflow

jobs:
  terraform-destroy:
    name: Destroy Terraform Resources
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Set AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init
        working-directory: ./ec2/ec2

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./ec2/ec2
